---
title: "TRGN 510 Final project-1"
output: html_notebook
---
setwd("~/TRGN-510-Final-Project")
setwd("final")
setwd("F2")
temp = list.files(pattern="*.txt")
F2<-lapply(temp, read.csv, sep="\t", header = FALSE)
setwd("~/TRGN-510-Final-Project")
setwd("final")
setwd("F3")
temp = list.files(pattern="*.txt")
F3<-lapply(temp, read.csv, sep="\t", header = FALSE)
setwd("~/TRGN-510-Final-Project")
setwd("final")
setwd("M2")
temp = list.files(pattern="*.txt")
M2<-lapply(temp, read.csv, sep="\t", header = FALSE)
setwd("~/TRGN-510-Final-Project")
setwd("final")
setwd("M3")
temp = list.files(pattern="*.txt")
M3<-lapply(temp, read.csv, sep="\t", header = FALSE)
ALL<-c(F2,F3,M2,M3)

aggregate <- function(listname) {
  res <- rowMeans(sapply(listname,function(x){
    return(x[,2])
  }))
  return(res)
}
all<-aggregate(ALL)
m2<-aggregate(M2)
m3<-aggregate(M3)
f2<-aggregate(F2)
f3<-aggregate(F3)
res<- data.frame(dev = m2-all, name=ALL[[1]][,1])
res$type<-ifelse(res$dev < 0, "below", "above")

library(ggplot2)
theme_set(theme_bw())  

# Diverging Barcharts
ggplot(res[1:20,], aes(x=name, y=dev, label=dev)) + 
  geom_bar(stat='identity', aes(fill=type), width=.5)  +
  scale_fill_manual(name="Deviation", 
                    labels = c("Above Average", "Below Average"), 
                    values = c("above"="#00ba38", "below"="#f8766d")) + 
  labs(subtitle="something", 
       title= "something") + 
  coord_flip()


